<script setup lang="ts">
import { onMounted, ref, reactive } from "vue";
import type { FormInstance } from "ant-design-vue";
import type { Rule } from "ant-design-vue/es/form";
import { NotificationError, NotificationSuccess } from "@/utils/notifications";
import { useCodeGenerationsStore } from "@/stores/codegenerations";
import { storeToRefs } from "pinia";
import CodeRequest from "@/model/CodeRequest";
import CodeResponse from "@/model/CodeResponse";

const codegenerationsStore = useCodeGenerationsStore();
const { generationStrategies, loading, generatingCode, errorMessages } =
	storeToRefs(codegenerationsStore);

const fetchStrategies = async () => {
	try {
		await codegenerationsStore.getGenerationStrategiesAsync();
	} catch (error) {
		console.error(error);
	} finally {
	}
};

onMounted(async () => {
	await fetchStrategies();
});

// ---------------- FORM ----------------

interface FormState {
	currentCode: string;
	newCode: string;
	inputText: string;
	strategy: string;
	useExpensiveModel: boolean;
}

const formState = reactive<FormState>({
	currentCode: "",
	newCode: "",
	inputText: "",
	strategy: "",
	useExpensiveModel: false
});

const formRef = ref<FormInstance>();

const rules: Record<string, Rule[]> = {
	inputText: [{ required: true, message: "Input text is required." }],
};

const onValidationFailed = (errorInfo: any) => {
	console.log("Validation failed:", errorInfo);
};

const submitForm = async () => {
	let codeRequest: CodeRequest | null = null;

	try {
		codeRequest = getCodeRequest(formState);
	} catch {
		errorMessages.value.push("Failed to create claim from form data.");
		console.log("Failed to create claim from form data.");
		return;
	}

	try {
		const newCode = await codegenerationsStore.generateCodeWithStrategy(
			codeRequest
		);

		formState.newCode = newCode;
	} catch (error) {
		errorMessages.value.push("Failed to create claim from form data.");
		console.log("Failed to create claim from form data.");
	}
};

function getCodeRequest(form: FormState): CodeRequest {
	const codeRequest = new CodeRequest();

	codeRequest.currentCode = form.currentCode;
	codeRequest.generationMethod = form.strategy;
	codeRequest.userInput = form.inputText;
	codeRequest.useExpensiveModel = form.useExpensiveModel;

	return codeRequest;
}

async function copyAndMoveUp() {
	try {
		await navigator.clipboard.writeText(formState.newCode);

		NotificationSuccess("Code Copied!", `Code copied to clipboard`);

		formState.currentCode = formState.newCode;
		formState.newCode = "";
	} catch (err) {
		console.error("Failed to copy text: ", err);
		NotificationError(
			"Failed copy code",
			`Code couldn't be copied to clipboard.`
		);
	}
}
</script>

<template>
	<div>
		<a-form
			:model="formState"
			:rules="rules"
			ref="formRef"
			layout="vertical"
			@finish="submitForm"
			@finishFailed="onValidationFailed"
		>
			<a-row>
				<a-col :span="24">
					<a-form-item
						label="Current Code"
						name="currentCode"
					>
						<a-input-group compact>
							<a-textarea
								v-model:value="formState.currentCode"
								placeholder="Please enter the current Sonic Pi code"
							/>
						</a-input-group>
					</a-form-item>
				</a-col>
			</a-row>
			<a-row>
				<a-col :span="24">
					<a-form-item
						label="Input Text"
						name="inputText"
					>
						<a-input-group compact>
							<a-input
								v-model:value="formState.inputText"
								placeholder="Please enter text input to GPT"
								required
							/>
						</a-input-group>
					</a-form-item>
				</a-col>
			</a-row>
			<a-row>
				<div v-if="errorMessages.values.length > 0">
					<p v-for="msg in errorMessages">
						{{ msg }}
					</p>
				</div>
			</a-row>
			<a-row>
				<a-col :span="16">
					<div class="form-buttons">
						<p class="keep-values-label">Use expensive model</p>
						<a-form-item>
							<a-switch v-model:checked="formState.useExpensiveModel" />
						</a-form-item>

						<a-form-item>
							<a-button
								type="primary"
								html-type="submit"
								>Submit</a-button
							>
						</a-form-item>
					</div>
				</a-col>
			</a-row>
			<a-row>
				<a-col :span="24">
					<a-form-item
						label="New code"
						name="newCode"
					>
						<a-input-group compact>
							<a-textarea
								v-model:value="formState.newCode"
								placeholder="Code generated by GPT"
							/>
						</a-input-group>
					</a-form-item>
				</a-col>
			</a-row>
			<a-row>
				<a-col :span="16">
					<div class="form-buttons">
						<a-form-item>
							<a-button
								class="form-button"
								@click="copyAndMoveUp"
								>Copy and move to current</a-button
							>
						</a-form-item>
					</div>
				</a-col>
			</a-row>
		</a-form>
	</div>

 	<p>
		 Loading: {{ loading }}
	</p>
	<p>
		GeneratingCode: {{ generatingCode }}
	</p>
	<p>
		ErrorMessages: {{ errorMessages }}
	</p>
</template>

<style scoped>
.form-buttons {
	display: flex;
	justify-content: end;
}

.form-button {
	margin-right: 1vw;
}
</style>
